language: "en_core_web_sm"

pipeline:
 - name: "nlp_spacy"
   model: "en"
 - name: "tokenizer_spacy"
 - name: "ner_crf"
 - name: "intent_featurizer_spacy"
 - name: "intent_classifier_sklearn"
 - name: "ner_synonyms"
 - name: "intent_entity_featurizer_regex"
 - name: "intent_featurizer_ngrams"
 - name: "tokenizer_whitespace"

 - name: "ner_duckling_http"
   url: "http://0.0.0.0:8000"
   locale: "da_DK"
   dimensions: ["time"]